"""
Django settings for remosphere project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, environ
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# LOGGING = {
#    "version": 1,
#    "disable_existing_loggers": False,
#
#    "formatters": {
#        "standard": {
#            "format": "[{asctime}] {levelname} {name}: {message}",
#            "style": "{",
#        },
#    },

#    "handlers": {
#        "file": {
#            "level": "INFO",
#            "class": "logging.FileHandler",
#            "filename": os.path.join(BASE_DIR, "logs", "django.log"),
#            "formatter": "standard",
#        },
#        "console": {
#            "class": "logging.StreamHandler",
#        },
#    },
#
#    "loggers": {
#        "django": {
#            "handlers": ["file", "console"],
#            "level": "INFO",
#            "propagate": True,
#       },
#        # Your project logs:
#        "": {
#            "handlers": ["file", "console"],
#            "level": "INFO",
#        },
#    },
#}

# Setting up environment
env = environ.Env()

# Detect environment mode
ENV_MODE = os.getenv("ENV_MODE", "development").lower()

if ENV_MODE == "production":
    env_file = os.path.join(BASE_DIR, ".env.production")
else:
    env_file = os.path.join(BASE_DIR, ".env.development")

# Read the chosen env file
env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG_MODE", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

SITE_URL = env("SITE_URL")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'categories',
    'jobs',
    'applications',
    'companies',
    'rest_framework',
    'drf_yasg',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    # 'authentication',
    'authentication.apps.AuthenticationConfig',
    'anymail',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'remosphere.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'remosphere.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("DB_NAME"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),
        'HOST': env("DB_HOST"),
        'PORT': env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        "NAME": "users.validators.StrongPasswordValidator"
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # fallback to header-only JWT
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
}

AUTH_USER_MODEL = 'users.User'

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Cookie settings (for cookies created by our login/refresh endpoints)
JWT_COOKIE_NAME = "remosphere_refresh"        # refresh stored HttpOnly cookie
JWT_ACCESS_COOKIE_NAME = "remosphere_access"  # access cookie
JWT_COOKIE_SECURE = env("JWT_COOKIE_SECURE")  # set to True in production (HTTPS)
JWT_COOKIE_SAMESITE = "Lax"                   # or "Strict"
JWT_COOKIE_HTTPONLY = True

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "JWTAuth": {
            "type": "apiKey",
            "in": "header",
            "name": "Authorization",
            "description": "Format: Bearer <token>"
        },

        # "Bearer": {
        #     "type": "apiKey",
        #     "name": "Authorization",
        #     "in": "header"
        # },
        # "CookieAuth": {                          # cookie-based in Swagger
        #     "type": "apiKey",
        #     "in": "cookie",
        #     "name": os.getenv("JWT_ACCESS_COOKIE_NAME", "remosphere_access")
        # }
    },
    "USE_SESSION_AUTH": False,
}

EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")

ANYMAIL = {
    "BREVO_API_KEY": env("BREVO_API_KEY"),
}

CELERY_BROKER_URL = env("CELERY_BROKER_URL")

# Password reset token lifetime (minutes)
PASSWORD_RESET_TOKEN_LIFETIME_MINUTES = env.int("PASSWORD_RESET_TOKEN_LIFETIME_MINUTES", 30)

# Rate limiting for password-reset requests
PASSWORD_RESET_RATE_LIMIT_PER_HOUR = env.int("PASSWORD_RESET_RATE_LIMIT_PER_HOUR", 5)
PASSWORD_RESET_RATE_LIMIT_IP_PER_HOUR = env.int("PASSWORD_RESET_RATE_LIMIT_IP_PER_HOUR", 20)

# secret for signing password-reset JWTs (you can reuse SECRET_KEY or use another env var)
PASSWORD_RESET_SIGNING_KEY = env("PASSWORD_RESET_SIGNING_KEY", default=SECRET_KEY)
PASSWORD_RESET_ALGORITHM = "HS256"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env("CELERY_BROKER_URL"),
    }
}