# Generated by Django 5.2.8 on 2025-11-26 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=128)),
                ('job_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('internship', 'Internship'), ('other', 'Other')], max_length=32)),
                ('salary_range', models.CharField(blank=True, max_length=64, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.URLField(blank=True, max_length=255, unique=True)),
                ('expiry_at', models.DateTimeField(blank=True, help_text='Optional expiry date after which is_active may be set to False.', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='categories.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='jobs_job_title_0e1e41_idx'), models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'), models.Index(fields=['category'], name='jobs_job_categor_24d294_idx'), models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx')],
            },
        ),
    ]
