# Generated by Django 5.2.8 on 2025-11-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('other', 'Other')], max_length=32),
        ),
    ]
