CREATE TYPE "role_enum" AS ENUM (
  'admin',
  'user'
);

CREATE TYPE "job_type_enum" AS ENUM (
  'full_time',
  'part_time',
  'contract',
  'internship',
  'temporary',
  'freelance'
);

CREATE TYPE "application_status_enum" AS ENUM (
  'pending',
  'reviewed',
  'shortlisted',
  'rejected',
  'offered',
  'withdrawn'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" role_enum DEFAULT 'user',
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "dob" date,
  "username" varchar(100) UNIQUE,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "is_admin" tinyint(1) DEFAULT 0,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP),
  "last_login" timestamp
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "companies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "website" varchar(255),
  "description" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "jobs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "slug" varchar(255) UNIQUE,
  "description" text,
  "category_id" int,
  "location_city" varchar(150),
  "location_state" varchar(150),
  "location_country" varchar(150),
  "is_remote" tinyint(1) DEFAULT 0,
  "type" job_type_enum DEFAULT 'full_time',
  "application_link" varchar(512),
  "salary_min" decimal(12,2),
  "salary_max" decimal(12,2),
  "company_name" varchar(255),
  "company_id" int,
  "created_by" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP),
  "is_active" tinyint(1) DEFAULT 1,
  "no_of_applications" int DEFAULT 0
);

CREATE TABLE "applications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" int NOT NULL,
  "user_id" int NOT NULL,
  "resume_url" varchar(512),
  "portfolio_url" varchar(512),
  "cover_letter_url" varchar(512),
  "cover_letter" text,
  "status" application_status_enum DEFAULT 'pending',
  "applied_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE INDEX ON "jobs" ("title");

CREATE INDEX ON "jobs" ("category_id");

CREATE INDEX ON "jobs" ("type");

CREATE INDEX ON "jobs" ("is_remote");

CREATE INDEX ON "jobs" ("created_at");

CREATE INDEX ON "applications" ("job_id");

CREATE INDEX ON "applications" ("user_id");

CREATE INDEX ON "applications" ("status");

COMMENT ON TABLE "users" IS 'Stores user data on signup, focusing on ALX Nigeria Alumni';

COMMENT ON COLUMN "users"."username" IS 'auto-generate (lower(firstname||lastname)) ensure uniqueness';

COMMENT ON COLUMN "users"."is_admin" IS 'derived from role on app side or DB trigger';

COMMENT ON TABLE "categories" IS 'Job categories / industries';

COMMENT ON TABLE "companies" IS 'Optional company profiles to associate with jobs';

COMMENT ON TABLE "jobs" IS 'Job postings';

COMMENT ON COLUMN "jobs"."category_id" IS 'FK -> categories.id';

COMMENT ON COLUMN "jobs"."application_link" IS 'external application link if using external apply';

COMMENT ON COLUMN "jobs"."company_id" IS 'FK -> companies.id (optional)';

COMMENT ON COLUMN "jobs"."created_by" IS 'FK -> users.id (who posted the job)';

COMMENT ON COLUMN "jobs"."no_of_applications" IS 'prefer view/materialized view or triggers to keep consistent';

COMMENT ON TABLE "applications" IS 'Job applications by users';

COMMENT ON COLUMN "applications"."job_id" IS 'FK -> jobs.id';

COMMENT ON COLUMN "applications"."user_id" IS 'FK -> users.id';

ALTER TABLE "jobs" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "jobs" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id");

ALTER TABLE "jobs" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "applications" ADD FOREIGN KEY ("job_id") REFERENCES "jobs" ("id");

ALTER TABLE "applications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
